---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Stornoway website'

Parameters:
  DomainName:
    Type: String
    Description: 'The domain name and the S3 bucket name at the same time'
    Default: 'cv.molnarbence.dev'

Resources:
  CloudFrontDistribution:
    UpdateReplacePolicy: 'Delete'
    Type: 'AWS::CloudFront::Distribution'
    DeletionPolicy: 'Delete'
    Properties:
      DistributionConfig:
        Logging:
          IncludeCookies: false
          Bucket: ''
          Prefix: ''
        Comment: ''
        DefaultRootObject: ''
        Origins:
          - ConnectionTimeout: 10
            OriginAccessControlId: ''
            ConnectionAttempts: 3
            OriginCustomHeaders: []
            DomainName: !Sub '${DomainName}.s3-website.eu-central-1.amazonaws.com'
            OriginShield:
              Enabled: false
            OriginPath: ''
            Id: 'cv.molnarbence.dev.s3.eu-central-1.amazonaws.com-mfwtonjt09o'
            CustomOriginConfig:
              IpAddressType: 'ipv4'
              OriginReadTimeout: 30
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginSSLProtocols:
                - 'SSLv3'
                - 'TLSv1'
                - 'TLSv1.1'
                - 'TLSv1.2'
              HTTPPort: 80
              OriginProtocolPolicy: 'http-only'
        ViewerCertificate:
          MinimumProtocolVersion: 'TLSv1.2_2021'
          SslSupportMethod: 'sni-only'
          # CloudFrontDefaultCertificate: false
          AcmCertificateArn: 'arn:aws:acm:us-east-1:230767735088:certificate/a5577866-3da5-4cca-8d0f-33815bfba0c2'
        PriceClass: 'PriceClass_All'
        DefaultCacheBehavior:
          Compress: true
          FunctionAssociations: []
          LambdaFunctionAssociations: []
          TargetOriginId: 'cv.molnarbence.dev.s3.eu-central-1.amazonaws.com-mfwtonjt09o'
          ViewerProtocolPolicy: 'redirect-to-https'
          GrpcConfig:
            Enabled: false
          TrustedSigners: []
          FieldLevelEncryptionId: ''
          TrustedKeyGroups: []
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          SmoothStreaming: false
          CachePolicyId:
            Ref: 'CloudFrontCachePolicy'
        Staging: false
        CustomErrorResponses: []
        ContinuousDeploymentPolicyId: ''
        OriginGroups:
          Quantity: 0
          Items: []
        Enabled: true
        Aliases:
          - 'cv.molnarbence.dev'
        IPV6Enabled: true
        WebACLId: ''
        HttpVersion: 'http2'
        Restrictions:
          GeoRestriction:
            Locations: []
            RestrictionType: 'none'
        CacheBehaviors: []

  AliasRecord:
    UpdateReplacePolicy: 'Delete'
    Type: 'AWS::Route53::RecordSet'
    DeletionPolicy: 'Delete'
    Properties:
      HostedZoneId: !ImportValue HostedZoneId-molnarbence-dev
      Name: !Sub '${DomainName}.'
      Type: 'A'
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  S3BucketCvmolnarbencedev:
    UpdateReplacePolicy: 'Delete'
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Delete'
    Properties:
      AbacStatus: 'Disabled'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
      BucketName: !Ref DomainName
      OwnershipControls:
        Rules:
          - ObjectOwnership: 'BucketOwnerEnforced'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

  S3BucketPolicyCvmolnarbencedev:
    UpdateReplacePolicy: 'Delete'
    Type: 'AWS::S3::BucketPolicy'
    DeletionPolicy: 'Delete'
    Properties:
      Bucket: !Ref S3BucketCvmolnarbencedev
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Resource: !Sub 'arn:aws:s3:::${DomainName}/*'
            Action: 's3:GetObject'
            Effect: 'Allow'
            Principal: '*'
            Sid: 'PublicReadGetObject'

  CloudFrontCachePolicy:
    UpdateReplacePolicy: 'Delete'
    Type: 'AWS::CloudFront::CachePolicy'
    DeletionPolicy: 'Delete'
    Properties:
      CachePolicyConfig:
        Comment: 'Policy with caching enabled. Supports Gzip and Brotli compression.'
        MinTTL: 1
        MaxTTL: 3.1536E7
        ParametersInCacheKeyAndForwardedToOrigin:
          QueryStringsConfig:
            QueryStringBehavior: 'none'
          EnableAcceptEncodingBrotli: true
          HeadersConfig:
            HeaderBehavior: 'none'
          CookiesConfig:
            CookieBehavior: 'none'
          EnableAcceptEncodingGzip: true
        DefaultTTL: 86400
        Name: 'Managed-CachingOptimized'

  StaticContentDeployRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'stornoway-static-content-deploy-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 'sts:AssumeRoleWithWebIdentity'
            Effect: 'Allow'
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub': 'repo:molnarbence/stornoway:*'
      Policies:
        - PolicyName: 's3-read-write'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                Resource:
                  - !Sub 'arn:aws:s3:::${DomainName}'
                  - !Sub 'arn:aws:s3:::${DomainName}/*'
        - PolicyName: 'cloudfront-invalidate'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'cloudfront:CreateInvalidation'
                Resource:
                  - !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

Outputs:
  StaticContentDeployRoleArn:
    Description: 'The ARN of the role to be assumed by GitHub Actions for deploying static content'
    Value: !GetAtt StaticContentDeployRole.Arn
